// Code generated by goplus from app.goml. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"fmt"
	"goforge.dev/palettegen/palette"
	"goforge.dev/palettegen/web"
	"io"
	"net/http"
	"os"
	"strings"
)

func sink(n int, e error) {
	return
}

func emit(w http.ResponseWriter, s string) {
	n, err := io.WriteString(w, s)
	sink(n, err)
}

func emitBytes(w http.ResponseWriter, bs []byte) {
	n, err := w.Write(bs)
	sink(n, err)
}

func modelFrom(r *http.Request) web.Model {
	return web.ModelFromValues(r.URL.Query(), false)
}

func handlePage(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
	} else {
		m := modelFrom(r)
		h := w.Header()
		h.Set("Content-Type", "text/html; charset=utf-8")
		emit(w, web.RenderPage(m))
	}
}

func handleCSS(w http.ResponseWriter, r *http.Request) {
	h := w.Header()
	h.Set("Content-Type", "text/css; charset=utf-8")
	emit(w, web.Stylesheet)
}

func handleFont(w http.ResponseWriter, r *http.Request) {
	bs := web.FontFor(r.URL.Path)
	if len(bs) == 0 {
		http.NotFound(w, r)
	} else {
		h := w.Header()
		h.Set("Content-Type", "font/woff2")
		h.Set("Cache-Control", "public, max-age=31536000, immutable")
		emitBytes(w, bs)
	}
}

func handleJSON(w http.ResponseWriter, r *http.Request) {
	m := modelFrom(r)
	h := w.Header()
	h.Set("Content-Type", "application/json")
	h.Set("Content-Disposition", "attachment; filename=\""+web.FileStem(m)+".json\"")
	emitBytes(w, palette.ToJSON(m.Pal))
}

func handlePDF(w http.ResponseWriter, r *http.Request) {
	m := modelFrom(r)
	h := w.Header()
	h.Set("Content-Type", "application/pdf")
	h.Set("Content-Disposition", "attachment; filename=\""+web.FileStem(m)+".pdf\"")
	err := palette.WritePDF(w, m.Pal)
	if err != nil {
		http.Error(w, "PDF generation failed", 500)
	} else {
		return
	}
}

func portFrom(env string) string {
	if strings.TrimSpace(env) == "" {
		return "8383"
	}
	return env
}

func main() {
	if len(os.Args) > 1 && os.Args[1] == "check" {
		os.Exit(web.RunChecks())
	}
	http.HandleFunc("/", handlePage)
	http.HandleFunc("/style.css", handleCSS)
	http.HandleFunc("/fonts/", handleFont)
	http.HandleFunc("/palette.json", handleJSON)
	http.HandleFunc("/palette.pdf", handlePDF)
	port := portFrom(os.Getenv("PORT"))
	fmt.Printf("Palette Forge %s listening on http://localhost:%s\n", web.Version, port)
	err := http.ListenAndServe(":"+port, nil)
	if err != nil {
		panic(err)
	} else {
		return
	}
}
