# Palette Forge — pure-goml build.
# Sources are the .goml files; every .go file here is generated by `goml gen`.

GOML ?= goml

.PHONY: gen build run check ci data fonts wasm site clean

gen:
	$(GOML) gen ./...

build: gen
	go build -o palettegen .

run: build
	./palettegen

check: build
	./palettegen check

# CI: fail if committed *_gml.go is stale, then build and self-check.
ci:
	$(GOML) gen -check ./...
	go build ./...
	go build -o palettegen . && ./palettegen check

# Regenerate palette/data.goml from the book extraction (tools/palettes.json).
data:
	python3 tools/gen_data.py
	$(MAKE) gen

# The WebAssembly build behind goforge.dev/palettegen/try.
wasm: gen
	GOOS=js GOARCH=wasm go build -o try/app.wasm ./try

# Copy the wasm and Go's runtime shim into the goforge.dev site checkout.
SITE ?= ../dev.goforge
site: wasm
	mkdir -p $(SITE)/static/palettegen/try
	cp try/app.wasm $(SITE)/static/palettegen/try/app.wasm
	cp "$$(go env GOROOT)/lib/wasm/wasm_exec.js" $(SITE)/static/palettegen/try/wasm_exec.js

# Re-download and re-embed the fonts (Overpass, Atkinson Hyperlegible).
fonts:
	python3 tools/gen_fonts.py
	$(MAKE) gen

clean:
	rm -f palettegen
