// Code generated by goplus from try.goml. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"fmt"
	"goforge.dev/palettegen/web"
	"os"
)

func main() {
	var __gp_v0 string
	if len(os.Args) > 1 {
		__gp_v0 = os.Args[1]
	} else {
		__gp_v0 = ""
	}
	search := __gp_v0
	m := web.ModelFromQuery(search, true)
	fmt.Print(web.RenderPage(m))
}
