// Code generated by goplus from book.goml. DO NOT EDIT.
//goplus:v v0.28.0

package palette

import (
	"fmt"
	"strconv"
	"strings"
)

// Book is one curated palette from the book, verbatim.
type Book struct {
	ID         int
	Name       string
	Primary    []Scale
	Neutrals   []Scale
	Supporting []Scale
}

func noScales() []Scale {
	return make([]Scale, 0)
}

func atoiOr(s string, fallback int) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		return fallback
	}
	return n
}

func appendParsed(shades []Shade, hx string) []Shade {
	switch __gp_m0 := any(ParseHex(hx)).(type) {
	case Good:
		sh := __gp_m0.Sh

		return append(shades, sh)
	case Bad:

		return shades
	default:
		panic("goplus: impossible enum value in match")
	}
}

func parseShades(packed string) []Shade {
	shades := make([]Shade, 0)
	for _, hx := range strings.Fields(packed) {
		shades = appendParsed(shades, hx)
	}
	return shades
}

// "Name|#HEX1 #HEX2 ..." -> Scale
func parseScaleLine(line string) Scale {
	parts := strings.Split(line, "|")
	return Scale{Name: parts[0], Shades: parseShades(parts[1])}
}

func buildReference() []Scale {
	out := make([]Scale, 0)
	for _, line := range refTable {
		out = append(out, parseScaleLine(line))
	}
	return out
}

func buildBook(pid int) Book {
	b := Book{ID: pid, Name: fmt.Sprintf("Palette %d", pid), Primary: noScales(), Neutrals: noScales(), Supporting: noScales()}
	for _, row := range curatedTable {
		parts := strings.Split(row, "|")
		if atoiOr(parts[0], 0) == pid {
			sc := Scale{Name: parts[2], Shades: parseShades(parts[3])}
			if parts[1] == "primary" {
				u1 := b
				u1.Primary = append(b.Primary, sc)
				b = u1
			} else {
				if parts[1] == "neutrals" {
					u2 := b
					u2.Neutrals = append(b.Neutrals, sc)
					b = u2
				} else {
					u3 := b
					u3.Supporting = append(b.Supporting, sc)
					b = u3
				}
			}
		}
	}
	return b
}

func buildCurated() []Book {
	out := make([]Book, 0)
	pid := 1
	for pid <= CuratedCount {
		out = append(out, buildBook(pid))
		pid = pid + 1
	}
	return out
}

var referenceScales = buildReference()

var curatedPalettes = buildCurated()

// Reference returns the book's closing reference section: 30 hand-tuned scales.
func Reference() []Scale {
	return referenceScales
}

// Curated returns the book's 24 palettes, verbatim.
func Curated() []Book {
	return curatedPalettes
}

// CuratedAt returns palette id (1-based); out-of-range ids clamp to 1.
func CuratedAt(id int) Book {
	if id < 1 || id > len(curatedPalettes) {
		return curatedPalettes[0]
	}
	return curatedPalettes[id-1]
}

// ColorSeeds returns the reference scales minus the grey families —
// the seed pool for generated primaries and accents.
func ColorSeeds() []Scale {
	out := make([]Scale, 0)
	for _, sc := range referenceScales {
		if strings.Contains(sc.Name, "Grey") {
		} else {
			out = append(out, sc)
		}
	}
	return out
}

func HasReference(name string) bool {
	found := false
	for _, sc := range referenceScales {
		if sc.Name == name {
			found = true
		}
	}
	return found
}

// ReferenceOr finds a reference scale by name, falling back to fallback.
func ReferenceOr(name string, fallback string) Scale {
	for _, sc := range referenceScales {
		if sc.Name == name {
			return sc
		}
	}
	for _, sc := range referenceScales {
		if sc.Name == fallback {
			return sc
		}
	}
	return referenceScales[0]
}

// CategoryDescription returns the book's paragraph for a category.
func CategoryDescription(cat string) string {
	if cat == "primary" {
		return DescPrimary
	}
	if cat == "neutrals" {
		return DescNeutrals
	}
	if cat == "supporting" {
		return DescSupporting
	}
	return ""
}
