// Code generated by goplus from color.goml. DO NOT EDIT.
//goplus:v v0.28.0

package palette

import (
	"fmt"
	"math"
	"strconv"
	"strings"
)

type RGB struct {
	R int
	G int
	B int
}

//goplus:enum Parsed
type Parsed interface{ isParsed() }

//goplus:variant (Parsed) Good(Sh Shade)
type Good struct {
	Sh Shade
}

func (Good) isParsed() {}

//goplus:variant (Parsed) Bad
type Bad struct{}

func (Bad) isParsed() {}

// ParsedCases selects one handler per Parsed variant for Fold.
type ParsedCases[R any] struct {
	Good func(Sh Shade) R
	Bad  func() R
}

// Fold reduces Parsed by one-level case analysis.
func Fold[R any](p Parsed, cs ParsedCases[R]) R {
	switch m := any(p).(type) {
	case Good:
		return cs.Good(m.Sh)
	case Bad:
		return cs.Bad()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// ParsedEqOverrides carries optional per-variant hooks for ParsedEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ParsedEqOverrides struct {
	Good func(x, y Good) (eq, handled bool)
	Bad  func(x, y Bad) (eq, handled bool)
}

// ParsedEqualWith reports structural equality of a and b under ov.
func ParsedEqualWith(a, b Parsed, ov ParsedEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Good:
		y, ok := any(b).(Good)
		if !ok {
			return false
		}
		if ov.Good != nil {
			if eq, handled := ov.Good(x, y); handled {
				return eq
			}
		}
		if x.Sh != y.Sh {
			return false
		}
		return true
	case Bad:
		y, ok := any(b).(Bad)
		if !ok {
			return false
		}
		if ov.Bad != nil {
			if eq, handled := ov.Bad(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ParsedEqual reports structural equality of a and b.
func ParsedEqual(a, b Parsed) bool {
	return ParsedEqualWith(a, b, ParsedEqOverrides{})
}

// Cross-package accessors (constructor patterns don't travel across packages).
func ParsedOk(p Parsed) bool {
	switch any(p).(type) {
	case Good:

		return true
	case Bad:

		return false
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ParsedShade(p Parsed) Shade {
	switch __gp_m1 := any(p).(type) {
	case Good:
		sh := __gp_m1.Sh

		return sh
	case Bad:

		return Shade{Hex: "#000000", H: 0.0, S: 0.0, L: 0.0}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func clamp01(x float64) float64 {
	if x < 0.0 {
		return 0.0
	}
	if x > 1.0 {
		return 1.0
	}
	return x
}

// hsl (degrees, percent, percent) -> rgb in 0..1
func hslChannel(p float64, q float64, t0 float64) float64 {
	var __gp_v0 float64
	if t0 < 0.0 {
		__gp_v0 = t0 + 1.0
	} else {
		var __gp_v1 float64
		if t0 > 1.0 {
			__gp_v1 = t0 - 1.0
		} else {
			__gp_v1 = t0
		}
		__gp_v0 = __gp_v1
	}
	t := __gp_v0
	if t < 1.0/6.0 {
		return p + (q-p)*6.0*t
	}
	if t < 0.5 {
		return q
	}
	if t < 2.0/3.0 {
		return p + (q-p)*(2.0/3.0-t)*6.0
	}
	return p
}

func hslToRGB(h float64, s float64, l float64) RGB {
	hh := normHue(h) / 360.0
	ss := clamp01(s / 100.0)
	ll := clamp01(l / 100.0)
	var __gp_v2 float64
	if ll < 0.5 {
		__gp_v2 = ll * (1.0 + ss)
	} else {
		__gp_v2 = ll + ss - ll*ss
	}
	q := __gp_v2
	p := 2.0*ll - q
	r := hslChannel(p, q, hh+1.0/3.0)
	g := hslChannel(p, q, hh)
	b := hslChannel(p, q, hh-1.0/3.0)
	return RGB{R: int(math.Round(r * 255.0)), G: int(math.Round(g * 255.0)), B: int(math.Round(b * 255.0))}
}

func HSLToHex(h float64, s float64, l float64) string {
	c := hslToRGB(h, s, l)
	return fmt.Sprintf("#%02X%02X%02X", c.R, c.G, c.B)
}

func MakeShade(h float64, s float64, l float64) Shade {
	return Shade{Hex: HSLToHex(h, s, l), H: math.Round(normHue(h)), S: math.Round(s), L: math.Round(l)}
}

func RGBOf(sh Shade) RGB {
	return hslToRGB(sh.H, sh.S, sh.L)
}

// Perceived brightness 0..255, the formula Refactoring UI cites:
// sqrt(0.299 R^2 + 0.587 G^2 + 0.114 B^2).
func LumaOf(sh Shade) float64 {
	c := RGBOf(sh)
	r := float64(c.R) / 255.0
	g := float64(c.G) / 255.0
	b := float64(c.B) / 255.0
	return math.Sqrt(0.299*r*r+0.587*g*g+0.114*b*b) * 255.0
}

func rgbToShade(hex string, r0 int, g0 int, b0 int) Shade {
	r := float64(r0) / 255.0
	g := float64(g0) / 255.0
	b := float64(b0) / 255.0
	mx := math.Max(r, math.Max(g, b))
	mn := math.Min(r, math.Min(g, b))
	l := (mx + mn) / 2.0
	d := mx - mn
	if d == 0.0 {
		return Shade{Hex: hex, H: 0.0, S: 0.0, L: math.Round(l * 100.0)}
	}
	var __gp_v3 float64
	if l > 0.5 {
		__gp_v3 = d / (2.0 - mx - mn)
	} else {
		__gp_v3 = d / (mx + mn)
	}
	s := __gp_v3
	var __gp_v4 float64
	if mx == r {
		__gp_v4 = math.Mod((g-b)/d, 6.0)
	} else {
		var __gp_v5 float64
		if mx == g {
			__gp_v5 = (b-r)/d + 2.0
		} else {
			__gp_v5 = (r-g)/d + 4.0
		}
		__gp_v4 = __gp_v5
	}
	hRaw := __gp_v4
	h := normHue(hRaw * 60.0)
	return Shade{Hex: hex, H: math.Round(h), S: math.Round(s * 100.0), L: math.Round(l * 100.0)}
}

func expand3(t string) string {
	return string(t[0]) + string(t[0]) + string(t[1]) + string(t[1]) + string(t[2]) + string(t[2])
}

// Parse "#RRGGBB" or "#RGB" (with or without '#', any case).
func ParseHex(raw string) Parsed {
	t0 := strings.ToLower(strings.TrimPrefix(strings.TrimSpace(raw), "#"))
	var __gp_v6 string
	if len(t0) == 3 {
		__gp_v6 = expand3(t0)
	} else {
		__gp_v6 = t0
	}
	t := __gp_v6
	if len(t) != 6 {
		return Bad{}
	}
	n, err := strconv.ParseInt(t, 16, 32)
	if err != nil {
		return Bad{}
	}
	v := int(n)
	r := v / 65536
	g := v / 256 % 256
	b := v % 256
	return Good{Sh: rgbToShade("#"+strings.ToUpper(t), r, g, b)}
}
