// Code generated by goplus from json.goml. DO NOT EDIT.
//goplus:v v0.28.0

package palette

import (
	"encoding/json"
)

type CategoryNotes struct {
	Primary    string `json:"primary"`
	Neutrals   string `json:"neutrals"`
	Supporting string `json:"supporting"`
}

type ExportDoc struct {
	Name       string        `json:"name"`
	Basis      string        `json:"basis"`
	Primary    []Scale       `json:"primary"`
	Neutrals   []Scale       `json:"neutrals"`
	Supporting []Scale       `json:"supporting"`
	Notes      CategoryNotes `json:"categoryNotes"`
}

func noBytes() []byte {
	return make([]byte, 0)
}

// ToJSON renders a palette as pretty JSON.
func ToJSON(p Palette) []byte {
	doc := ExportDoc{Name: p.Name, Basis: p.Basis, Primary: p.Primary, Neutrals: p.Neutrals, Supporting: p.Supporting, Notes: CategoryNotes{Primary: DescPrimary, Neutrals: DescNeutrals, Supporting: DescSupporting}}
	bs, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return noBytes()
	}
	return bs
}
