// Code generated by goplus from palette.goml. DO NOT EDIT.
//goplus:v v0.28.0

package palette

import (
	"fmt"
	"math"
	"strings"
)

type Shade struct {
	Hex string  `json:"hex"`
	H   float64 `json:"h"`
	S   float64 `json:"s"`
	L   float64 `json:"l"`
}

type Scale struct {
	Name   string  `json:"name"`
	Shades []Shade `json:"shades"`
}

type Palette struct {
	Name       string  `json:"name"`
	Basis      string  `json:"basis"`
	Primary    []Scale `json:"primary"`
	Neutrals   []Scale `json:"neutrals"`
	Supporting []Scale `json:"supporting"`
}

// Circular distance between two hues, in degrees.
func HueDistance(a float64, b float64) float64 {
	d := math.Abs(a - b)
	return math.Min(d, 360.0-d)
}

// Signed shortest rotation taking hue a to hue b, in [-180, 180].
func hueDelta(a float64, b float64) float64 {
	d := b - a
	for d > 180.0 {
		d = d - 360.0
	}
	for d < -180.0 {
		d = d + 360.0
	}
	return d
}

func normHue(h float64) float64 {
	x := h
	for x >= 360.0 {
		x = x - 360.0
	}
	for x < 0.0 {
		x = x + 360.0
	}
	return x
}

func clampPct(x float64) float64 {
	if x < 0.0 {
		return 0.0
	}
	if x > 100.0 {
		return 100.0
	}
	return x
}

// The shade of a scale whose lightness is closest to l.
func AnchorIndex(sc Scale, l float64) int {
	best := 0
	bestDist := 1000.0
	for i, sh := range sc.Shades {
		d := math.Abs(sh.L - l)
		if d < bestDist {
			best = i
			bestDist = d
		}
	}
	return best
}

// How far a scale's character sits from a requested color: hue dominates,
// saturation class breaks ties (so a muted request finds a muted seed).
func scaleDistance(base Shade, sc Scale) float64 {
	mid := sc.Shades[4]
	return HueDistance(base.H, mid.H) + math.Abs(base.S-mid.S)*0.35
}

func Nearest(base Shade, seeds []Scale) Scale {
	best := seeds[0]
	bestDist := 100000.0
	for _, sc := range seeds {
		d := scaleDistance(base, sc)
		if d < bestDist {
			best = sc
			bestDist = d
		}
	}
	return best
}

// Re-anchor a hand-tuned seed scale onto a requested color. The requested
// color lands exactly on the shade nearest its lightness; hue is rotated
// uniformly; saturation and lightness corrections fade out toward the two
// ends of the scale so the seed's usable-as-text darks and tinted-background
// lights (the book's rule for shades 900 and 50) survive intact.
func ShiftScale(seed Scale, base Shade, name string) Scale {
	a := AnchorIndex(seed, base.L)
	anchor := seed.Shades[a]
	dh := hueDelta(anchor.H, base.H)
	dl := base.L - anchor.L
	var __gp_v0 float64
	if anchor.S > 0.0 {
		__gp_v0 = base.S / anchor.S
	} else {
		__gp_v0 = 1.0
	}
	ratio := __gp_v0
	far := math.Max(float64(a), float64(len(seed.Shades)-1-a))
	out := make([]Shade, 0)
	for i, sh := range seed.Shades {
		var __gp_v1 float64
		if far > 0.0 {
			__gp_v1 = 1.0 - math.Abs(float64(i-a))/far
		} else {
			__gp_v1 = 1.0
		}
		w := __gp_v1
		h2 := normHue(sh.H + dh)
		s2 := clampPct(sh.S * (1.0 + (ratio-1.0)*w))
		l2 := clampPct(sh.L + dl*w)
		out = append(out, MakeShade(h2, s2, l2))
	}
	return Scale{Name: name, Shades: out}
}

// Name a hue the way the book names its scales.
func HueName(h float64, s float64) string {
	var __gp_v2 string
	if h < 15.0 {
		__gp_v2 = "Red"
	} else {
		var __gp_v3 string
		if h < 40.0 {
			__gp_v3 = "Orange"
		} else {
			var __gp_v4 string
			if h < 70.0 {
				__gp_v4 = "Yellow"
			} else {
				var __gp_v5 string
				if h < 95.0 {
					__gp_v5 = "Lime Green"
				} else {
					var __gp_v6 string
					if h < 150.0 {
						__gp_v6 = "Green"
					} else {
						var __gp_v7 string
						if h < 175.0 {
							__gp_v7 = "Teal"
						} else {
							var __gp_v8 string
							if h < 195.0 {
								__gp_v8 = "Cyan"
							} else {
								var __gp_v9 string
								if h < 215.0 {
									__gp_v9 = "Light Blue"
								} else {
									var __gp_v10 string
									if h < 250.0 {
										__gp_v10 = "Blue"
									} else {
										var __gp_v11 string
										if h < 275.0 {
											__gp_v11 = "Indigo"
										} else {
											var __gp_v12 string
											if h < 305.0 {
												__gp_v12 = "Purple"
											} else {
												var __gp_v13 string
												if h < 330.0 {
													__gp_v13 = "Magenta"
												} else {
													var __gp_v14 string
													if h < 345.0 {
														__gp_v14 = "Pink"
													} else {
														__gp_v14 = "Red"
													}
													__gp_v13 = __gp_v14
												}
												__gp_v12 = __gp_v13
											}
											__gp_v11 = __gp_v12
										}
										__gp_v10 = __gp_v11
									}
									__gp_v9 = __gp_v10
								}
								__gp_v8 = __gp_v9
							}
							__gp_v7 = __gp_v8
						}
						__gp_v6 = __gp_v7
					}
					__gp_v5 = __gp_v6
				}
				__gp_v4 = __gp_v5
			}
			__gp_v3 = __gp_v4
		}
		__gp_v2 = __gp_v3
	}
	base := __gp_v2
	if s >= 70.0 {
		return base + " (Vivid)"
	}
	return base
}

// The book's grey families, chosen by the primary hue's temperature.
func greyFamilyFor(h float64) string {
	if h < 20.0 {
		return "Warm Grey"
	}
	if h < 160.0 {
		return "Grey"
	}
	if h < 260.0 {
		return "Blue Grey"
	}
	if h < 330.0 {
		return "Cool Grey"
	}
	return "Warm Grey"
}

// Pick the semantic variant (plain vs Vivid) matching the base's intensity.
func semanticName(base string, s float64) string {
	if s >= 60.0 {
		return base + " (Vivid)"
	}
	return base
}

// Build a complete palette around one requested color, following the book's
// prescription: one primary scale, temperature-matched neutrals, semantic
// red/yellow/green scales, plus a complementary accent scale.
func Generate(base Shade) Palette {
	seed := Nearest(base, ColorSeeds())
	primaryName := HueName(base.H, base.S)
	primary := ShiftScale(seed, base, primaryName)
	neutral := ReferenceOr(greyFamilyFor(base.H), "Grey")
	supporting := make([]Scale, 0)
	accentHue := normHue(base.H + 180.0)
	accentShade := Shade{Hex: "", H: accentHue, S: base.S, L: base.L}
	accentSeed := Nearest(accentShade, ColorSeeds())
	accent := ShiftScale(accentSeed, accentShade, HueName(accentHue, base.S))
	supporting = append(supporting, accent)
	sems := []string{semanticName("Red", base.S), semanticName("Yellow", base.S), semanticName("Green", base.S)}
	for _, sem := range sems {
		if HasReference(sem) {
			sc := ReferenceOr(sem, "Grey")
			if HueDistance(base.H, sc.Shades[4].H) > 25.0 {
				supporting = append(supporting, sc)
			}
		}
	}
	return Palette{Name: primaryName + " " + strings.ToUpper(base.Hex), Basis: fmt.Sprintf("Generated from %s using the Refactoring UI methodology (seed scale: %s)", strings.ToUpper(base.Hex), seed.Name), Primary: []Scale{primary}, Neutrals: []Scale{neutral}, Supporting: supporting}
}

// A curated palette from the book, verbatim.
func FromCurated(id int) Palette {
	bp := CuratedAt(id)
	return Palette{Name: bp.Name, Basis: "Refactoring UI: Color Palettes v1.1.0, " + bp.Name + " (verbatim)", Primary: bp.Primary, Neutrals: bp.Neutrals, Supporting: bp.Supporting}
}
