// Code generated by goplus from pdf.goml. DO NOT EDIT.
//goplus:v v0.28.0

package palette

import (
	"codeberg.org/go-pdf/fpdf"
	"fmt"
	"io"
	"time"
)

var pageW float64 = 297.0

var pageH float64 = 210.0

var marginX float64 = 20.0

// Ink colors: the darkest and mid blue-grey neutrals from the book.
var inkDark = RGB{R: 16, G: 42, B: 67}

var inkMid = RGB{R: 98, G: 125, B: 152}

var inkPale = RGB{R: 240, G: 244, B: 248}

var inkWhite = RGB{R: 255, G: 255, B: 255}

type Section struct {
	Title  string
	Desc   string
	Scales []Scale
}

func mixInk(a RGB, b RGB, t float64) RGB {
	f := func(x int, y int) int { return int(float64(x)*(1.0-t) + float64(y)*t) }
	return RGB{R: f(a.R, b.R), G: f(a.G, b.G), B: f(a.B, b.B)}
}

func allScales(p Palette) []Scale {
	out := make([]Scale, 0)
	for _, sc := range p.Primary {
		out = append(out, sc)
	}
	for _, sc := range p.Neutrals {
		out = append(out, sc)
	}
	for _, sc := range p.Supporting {
		out = append(out, sc)
	}
	return out
}

func coverPage(pdf *fpdf.Fpdf, p Palette) {
	pdf.AddPage()
	bg := inkDark
	fg := inkPale
	if len(p.Neutrals) > 0 && len(p.Neutrals[0].Shades) == 10 {
		bg = RGBOf(p.Neutrals[0].Shades[0])
		fg = RGBOf(p.Neutrals[0].Shades[9])
	}
	pdf.SetFillColor(bg.R, bg.G, bg.B)
	pdf.Rect(0.0, 0.0, pageW, pageH, "F")
	pdf.SetTextColor(fg.R, fg.G, fg.B)
	pdf.SetFont("Helvetica", "", 12.0)
	pdf.Text(marginX, 40.0, "UI Color Palette")
	pdf.SetFont("Helvetica", "B", 34.0)
	pdf.Text(marginX, 56.0, p.Name)
	faded := mixInk(fg, bg, 0.35)
	pdf.SetFont("Helvetica", "", 10.0)
	pdf.SetTextColor(faded.R, faded.G, faded.B)
	pdf.Text(marginX, 66.0, p.Basis)
	pdf.Text(marginX, 72.0, "Generated "+time.Now().Format("2 January 2006")+" - after Refactoring UI: Color Palettes (Wathan & Schoger)")
	scales := allScales(p)
	if len(scales) == 0 {
		return
	} else {
		stripW := (pageW - 2.0*marginX) / float64(len(scales))
		y := pageH - 70.0
		for i, sc := range scales {
			if len(sc.Shades) < 10 {
			} else {
				j := 0
				for j < 5 {
					c := RGBOf(sc.Shades[1+j*2])
					pdf.SetFillColor(c.R, c.G, c.B)
					pdf.Rect(marginX+float64(i)*stripW, y+float64(j)*8.0, stripW-3.0, 8.0, "F")
					j = j + 1
				}
			}
		}
	}
}

func scalePage(pdf *fpdf.Fpdf, p Palette, sec Section, idx int, count int, sc Scale) {
	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 9.0)
	pdf.SetTextColor(inkMid.R, inkMid.G, inkMid.B)
	pdf.Text(marginX, 18.0, fmt.Sprintf("%s  -  UI Color Palette", p.Name))
	var __gp_v0 string
	if count > 1 {
		__gp_v0 = fmt.Sprintf("%s %d of %d", sec.Title, idx+1, count)
	} else {
		__gp_v0 = sec.Title
	}
	title := __gp_v0
	pdf.SetFont("Helvetica", "B", 24.0)
	pdf.SetTextColor(inkDark.R, inkDark.G, inkDark.B)
	pdf.Text(marginX, 34.0, title)
	pdf.SetFont("Helvetica", "", 10.5)
	pdf.SetTextColor(inkMid.R, inkMid.G, inkMid.B)
	pdf.SetXY(marginX, 40.0)
	pdf.MultiCell(175.0, 5.2, sec.Desc, "", "L", false)
	pdf.SetFont("Helvetica", "B", 15.0)
	pdf.SetTextColor(inkDark.R, inkDark.G, inkDark.B)
	nameW := pdf.GetStringWidth(sc.Name)
	pdf.Text(pageW-marginX-nameW, 34.0, sc.Name)
	top := 68.0
	gap := 4.0
	cellH := 22.0
	colW := (pageW - 2.0*marginX - 8.0) / 2.0
	for i, sh := range sc.Shades {
		col := i / 5
		row := i % 5
		x := marginX + float64(col)*(colW+8.0)
		y := top + float64(row)*(cellH+gap)
		c := RGBOf(sh)
		pdf.SetFillColor(c.R, c.G, c.B)
		pdf.RoundedRect(x, y, colW, cellH, 2.5, "1234", "F")
		var __gp_v1 RGB
		if LumaOf(sh) > 150.0 {
			__gp_v1 = inkDark
		} else {
			__gp_v1 = inkWhite
		}
		ink := __gp_v1
		pdf.SetTextColor(ink.R, ink.G, ink.B)
		cy := y + cellH/2.0 + 1.6
		pdf.SetFont("Helvetica", "", 10.0)
		pdf.Text(x+7.0, cy, fmt.Sprintf("hsl(%d, %d%%, %d%%)", int(sh.H), int(sh.S), int(sh.L)))
		pdf.SetFont("Courier", "B", 11.0)
		hexW := pdf.GetStringWidth(sh.Hex)
		pdf.Text(x+colW-7.0-hexW, cy, sh.Hex)
	}
	pdf.SetFont("Helvetica", "", 8.0)
	pdf.SetTextColor(inkMid.R, inkMid.G, inkMid.B)
	pdf.Text(marginX, pageH-12.0, "Shades run darkest (900) to lightest (50). Method: Refactoring UI, chapter on building color palettes.")
}

// WritePDF renders the palette to w. Returns nil on success.
func WritePDF(w io.Writer, p Palette) error {
	pdf := fpdf.New("L", "mm", "A4", "")
	pdf.SetTitle(p.Name+" - UI Color Palette", true)
	pdf.SetAutoPageBreak(false, 0.0)
	coverPage(pdf, p)
	sections := []Section{Section{Title: "Primary", Desc: DescPrimary, Scales: p.Primary}, Section{Title: "Neutrals", Desc: DescNeutrals, Scales: p.Neutrals}, Section{Title: "Supporting", Desc: DescSupporting, Scales: p.Supporting}}
	for _, sec := range sections {
		for i, sc := range sec.Scales {
			scalePage(pdf, p, sec, i, len(sec.Scales), sc)
		}
	}
	return pdf.Output(w)
}
