#!/usr/bin/env python3
"""Regenerate palette/data.goml from palettes.json (extracted from
"Refactoring UI: Color Palettes v1.1.0"). Build-time tool only — the app
itself is pure goml. Run: python3 tools/gen_data.py"""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "palettes.json")))

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def scale_line(sc):
    hexes = " ".join(sh["hex"].upper() for sh in sc["shades"])
    return f'{sc["name"]}|{hexes}'

lines = []
lines.append("module palette")
lines.append("")
lines.append("-- GENERATED by tools/gen_data.py from tools/palettes.json")
lines.append('-- (data extracted from "Refactoring UI: Color Palettes v1.1.0"')
lines.append("-- by Adam Wathan & Steve Schoger). Hex values are verbatim from")
lines.append("-- the book; hsl components are recomputed by ParseHex, which the")
lines.append("-- extraction validated to within the book's own rounding (±1).")
lines.append("")

d = data["categoryDescriptions"]
lines.append(f'let DescPrimary : String := "{esc(d["primary"])}"')
lines.append("")
lines.append(f'let DescNeutrals : String := "{esc(d["neutrals"])}"')
lines.append("")
lines.append(f'let DescSupporting : String := "{esc(d["supporting"])}"')
lines.append("")

lines.append("-- The book's closing reference section: 30 hand-tuned scales,")
lines.append("-- each ten shades darkest to lightest.")
lines.append("let refTable : Slice String := [")
rows = [f'  "{esc(scale_line(sc))}"' for sc in data["swatches"]]
lines.append(",\n".join(rows))
lines.append("]")
lines.append("")

lines.append("-- The book's 24 curated palettes: id|category|name|shades.")
lines.append("let curatedTable : Slice String := [")
rows = []
for p in data["palettes"]:
    for cat in ("primary", "neutrals", "supporting"):
        for sc in p[cat]:
            rows.append(f'  "{p["id"]}|{cat}|{esc(scale_line(sc))}"')
lines.append(",\n".join(rows))
lines.append("]")
lines.append("")
lines.append(f'let CuratedCount : Int := {len(data["palettes"])}')

out = os.path.join(here, "..", "palette", "data.goml")
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {os.path.normpath(out)}: {len(data['swatches'])} reference scales, "
      f"{sum(len(p[c]) for p in data['palettes'] for c in ('primary','neutrals','supporting'))} curated scale rows")
