#!/usr/bin/env python3
"""Regenerate fonts.goml: downloads the latin woff2 subsets of Overpass 700
and Atkinson Hyperlegible 400/700/400-italic from Google Fonts and embeds
them as base64. Build-time tool only - the app itself is pure goml.
Both families are licensed under the SIL Open Font License 1.1.
Run: python3 tools/gen_fonts.py"""
import base64, os, re, urllib.request

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

FAMILIES = [
    ("overpass700", "https://fonts.googleapis.com/css2?family=Overpass:wght@700&display=swap", "normal", "700"),
    ("atkinson400", "https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400&display=swap", "normal", "400"),
    ("atkinson700", "https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@700&display=swap", "normal", "700"),
    ("atkinson400i", "https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@1,400&display=swap", "italic", "400"),
]

def latin_woff2(css):
    # blocks: /* latin */ @font-face { ... url(...woff2) ... }
    blocks = re.findall(r'/\*\s*(\S+)\s*\*/\s*@font-face\s*{(.*?)}', css, re.S)
    for tag, body in blocks:
        if tag == "latin":
            return re.search(r'url\((https://[^)]+\.woff2)\)', body).group(1)
    # fallback: last block
    return re.findall(r'url\((https://[^)]+\.woff2)\)', css)[-1]

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req).read()

here = os.path.dirname(os.path.abspath(__file__))
lines = [
    "module main",
    "",
    "-- GENERATED by tools/gen_fonts.py - woff2 latin subsets, base64.",
    "-- Overpass (c) the Overpass Project; Atkinson Hyperlegible (c) Braille",
    "-- Institute of America. Both under the SIL Open Font License 1.1.",
    "",
]
for name, cssurl, style, weight in FAMILIES:
    css = fetch(cssurl).decode()
    url = latin_woff2(css)
    data = fetch(url)
    b64 = base64.b64encode(data).decode()
    print(f"{name}: {len(data)} bytes from {url}")
    lines.append(f'let {name}B64 : String := "{b64}"')
    lines.append("")

out = os.path.join(here, "..", "fonts.goml")
open(out, "w").write("\n".join(lines))
print("wrote", os.path.normpath(out))
