// Code generated by goplus from check.goml. DO NOT EDIT.
//goplus:v v0.28.0

package web

import (
	"fmt"
	"goforge.dev/palettegen/palette"
	"io"
	"strings"
)

func check(name string, ok bool) int {
	if ok {
		return 0
	}
	fmt.Println("FAIL: " + name)
	return 1
}

func shadesMonotonic(sc palette.Scale) bool {
	good := true
	i := 1
	for i < len(sc.Shades) {
		if sc.Shades[i].L <= sc.Shades[i-1].L {
			good = false
		}
		i = i + 1
	}
	return good
}

func anchorPreserved(base palette.Shade, sc palette.Scale) bool {
	found := false
	for _, sh := range sc.Shades {
		if sh.H == base.H && sh.S == base.S && sh.L == base.L {
			found = true
		}
	}
	return found
}

func allTenShades(scales []palette.Scale) bool {
	good := true
	for _, sc := range scales {
		if len(sc.Shades) != 10 {
			good = false
		}
	}
	return good
}

func foundScale(ms MaybeScale) bool {
	switch any(ms).(type) {
	case ScaleSome:

		return true
	case ScaleNone:

		return false
	default:
		panic("goplus: impossible enum value in match")
	}
}

func RunChecks() int {
	fails := 0
	fails = fails + check("24 curated palettes", len(palette.Curated()) == 24)
	fails = fails + check("30 reference scales", len(palette.Reference()) == 30)
	fails = fails + check("reference scales all have 10 shades", allTenShades(palette.Reference()))
	fails = fails + check("seed pool excludes greys", len(palette.ColorSeeds()) == 26)
	p1 := palette.FromCurated(1)
	fails = fails + check("palette 1 primary is Cyan", len(p1.Primary) == 1 && p1.Primary[0].Name == "Cyan")
	fails = fails + check("palette 1 darkest cyan is #044E54", p1.Primary[0].Shades[0].Hex == "#044E54")
	fails = fails + check("palette 1 has 4 supporting scales", len(p1.Supporting) == 4)
	parsed := palette.ParseHex("#2CB1BC")
	fails = fails + check("parse #2CB1BC ok", palette.ParsedOk(parsed))
	sh := palette.ParsedShade(parsed)
	fails = fails + check("hsl of #2CB1BC is (185, 62, 45)", sh.H == 185.0 && sh.S == 62.0 && sh.L == 45.0)
	fails = fails + check("short and unhashed hex parse", palette.ParsedOk(palette.ParseHex("fff")) && palette.ParsedOk(palette.ParseHex("7C3AED")))
	fails = fails + check("garbage hex rejected", !palette.ParsedOk(palette.ParseHex("zzz")) && !palette.ParsedOk(palette.ParseHex("#12345")))
	red := palette.ParsedShade(palette.ParseHex("#D64545"))
	gen := palette.Generate(red)
	fails = fails + check("generated primary has 10 shades", len(gen.Primary) == 1 && len(gen.Primary[0].Shades) == 10)
	fails = fails + check("generated primary lightness is monotonic", shadesMonotonic(gen.Primary[0]))
	fails = fails + check("requested color survives as an anchor shade", anchorPreserved(red, gen.Primary[0]))
	fails = fails + check("red primary keeps warm grey neutrals", len(gen.Neutrals) == 1 && gen.Neutrals[0].Name == "Warm Grey")
	fails = fails + check("red primary skips the red semantic scale", len(gen.Supporting) == 3)
	pool := contextScales(gen)
	fails = fails + check("success alert scale found", foundScale(findScale(pool, isSuccessHue)))
	fails = fails + check("warning alert scale found", foundScale(findScale(pool, isWarningHue)))
	fails = fails + check("danger falls back to the red primary", foundScale(findScale(pool, isDangerHue)))
	fails = fails + check("theme sanitizer", sanitizeTheme("dark") == "dark" && sanitizeTheme("light") == "light" && sanitizeTheme("purple") == "")
	fails = fails + check("html escaping", escapeHTML("a<b>&c") == "a&lt;b&gt;&amp;c")
	genTheme := ThemeCSS(gen)
	fails = fails + check("chrome tokens come from the generated palette", strings.Contains(genTheme, gen.Primary[0].Shades[2].Hex) && strings.Contains(genTheme, gen.Neutrals[0].Shades[0].Hex))
	fails = fails + check("chrome has light, auto-dark and pinned-dark blocks", strings.Contains(genTheme, "@media (prefers-color-scheme: dark)") && strings.Contains(genTheme, ":root[data-theme=dark]"))
	fails = fails + check("palette 1 chrome keeps the cyan accent", strings.Contains(ThemeCSS(p1), "--accent: #0E7C86"))
	page := RenderPage(curatedModel(1, "", "", false))
	fails = fails + check("no href=# anchors on the page", !strings.Contains(page, "href=\"#\""))
	fails = fails + check("demo buttons are type=button", strings.Contains(page, "<button type=\"button\" class=\"demo-btn\""))
	fails = fails + check("demo form fields are real inputs", strings.Contains(page, "class=\"mock-input\" placeholder="))
	fails = fails + check("hero carries version pill and install command", strings.Contains(page, Version) && strings.Contains(page, "go install goforge.dev/palettegen@latest"))
	fails = fails + check("hero links repo and pkg.go.dev", strings.Contains(page, "github.com/brain-fuel/palettegen") && strings.Contains(page, "pkg.go.dev/goforge.dev/palettegen"))
	fails = fails + check("overpass 700 decodes as woff2", len(overpass700) > 1000 && strings.HasPrefix(string(overpass700), "wOF2"))
	fails = fails + check("atkinson faces decode as woff2", strings.HasPrefix(string(atkinson400), "wOF2") && strings.HasPrefix(string(atkinson700), "wOF2") && strings.HasPrefix(string(atkinson400i), "wOF2"))
	fails = fails + check("stylesheet wires both families", strings.Contains(Stylesheet, "font-family: 'Overpass'") && strings.Contains(Stylesheet, "'Atkinson Hyperlegible'"))
	fails = fails + check("unknown font path yields empty", len(FontFor("/fonts/nope.woff2")) == 0)
	epage := RenderPage(curatedModel(1, "", "", true))
	fails = fails + check("embed page inlines all CSS, links none", strings.Contains(epage, "data:font/woff2;base64,") && !strings.Contains(epage, "<link rel=\"stylesheet\""))
	fails = fails + check("embed page hands out data: downloads", strings.Contains(epage, "data:application/pdf;base64,") && strings.Contains(epage, "data:application/json;base64,"))
	fails = fails + check("server page keeps relative endpoint links", strings.Contains(page, "href=\"palette.pdf?p=1\"") && strings.Contains(page, "href=\"style.css\""))
	fails = fails + check("json export is non-empty", len(palette.ToJSON(gen)) > 500)
	pdfErr := palette.WritePDF(io.Discard, gen)
	fails = fails + check("pdf renders without error", pdfErr == nil)
	if fails == 0 {
		fmt.Println("all checks passed")
	} else {
		fmt.Printf("%d check(s) failed\n", fails)
	}
	return fails
}
