// Code generated by goplus from fontserve.goml. DO NOT EDIT.
//goplus:v v0.28.0

package web

import (
	"encoding/base64"
)

func noFontBytes() []byte {
	return make([]byte, 0)
}

func decodeFont(s string) []byte {
	enc := base64.StdEncoding
	bs, err := enc.DecodeString(s)
	if err != nil {
		return noFontBytes()
	}
	return bs
}

var overpass700 = decodeFont(overpass700B64)

var atkinson400 = decodeFont(atkinson400B64)

var atkinson700 = decodeFont(atkinson700B64)

var atkinson400i = decodeFont(atkinson400iB64)

// FontFor maps a request path to font bytes; empty means not found.
func FontFor(p string) []byte {
	if p == "/fonts/overpass-700.woff2" {
		return overpass700
	}
	if p == "/fonts/atkinson-400.woff2" {
		return atkinson400
	}
	if p == "/fonts/atkinson-700.woff2" {
		return atkinson700
	}
	if p == "/fonts/atkinson-400-italic.woff2" {
		return atkinson400i
	}
	return noFontBytes()
}
