// Code generated by goplus from model.goml. DO NOT EDIT.
//goplus:v v0.28.0

package web

import (
	"fmt"
	"goforge.dev/palettegen/palette"
	"net/url"
	"strconv"
	"strings"
)

var Version string = "v0.2.0"

type Model struct {
	Mode      string
	Hex       string
	CuratedID int
	QS        string
	Note      string
	Theme     string
	Embed     bool
	Pal       palette.Palette
}

// "light" and "dark" are honored; anything else means "follow the OS".
func sanitizeTheme(t string) string {
	if t == "light" || t == "dark" {
		return t
	}
	return ""
}

func parseIntOr(s string, fallback int) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		return fallback
	}
	return n
}

// The color the picker should show: the current palette's base primary.
func pickerHex(m Model) string {
	if m.Mode == "generated" {
		return m.Hex
	}
	if len(m.Pal.Primary) > 0 && len(m.Pal.Primary[0].Shades) == 10 {
		return m.Pal.Primary[0].Shades[4].Hex
	}
	return "#2CB1BC"
}

func curatedModel(id int, note string, theme string, embed bool) Model {
	return Model{Mode: "curated", Hex: "", CuratedID: id, QS: fmt.Sprintf("p=%d", id), Note: note, Theme: theme, Embed: embed, Pal: palette.FromCurated(id)}
}

func generatedModel(sh palette.Shade, theme string, embed bool) Model {
	return Model{Mode: "generated", Hex: sh.Hex, CuratedID: 0, QS: "c=" + strings.TrimPrefix(sh.Hex, "#"), Note: "", Theme: theme, Embed: embed, Pal: palette.Generate(sh)}
}

// The freshly-typed hex wins over the picker; empty means "not given".
func pickColor(hx string, c string) string {
	if strings.TrimSpace(hx) != "" {
		return hx
	}
	return c
}

// ModelFromValues builds the page model from URL query parameters.
func ModelFromValues(q url.Values, embed bool) Model {
	theme := sanitizeTheme(q.Get("t"))
	pRaw := q.Get("p")
	colorRaw := pickColor(q.Get("hx"), q.Get("c"))
	if pRaw != "" {
		id := parseIntOr(pRaw, 0)
		if id >= 1 && id <= len(palette.Curated()) {
			return curatedModel(id, "", theme, embed)
		}
		return curatedModel(1, "That palette number does not exist - showing Palette 1.", theme, embed)
	}
	if strings.TrimSpace(colorRaw) != "" {
		parsed := palette.ParseHex(colorRaw)
		if palette.ParsedOk(parsed) {
			return generatedModel(palette.ParsedShade(parsed), theme, embed)
		}
		return curatedModel(1, "Could not read that color - showing Palette 1 instead. Try a hex like #7C3AED.", theme, embed)
	}
	return curatedModel(1, "", theme, embed)
}

// ModelFromQuery parses a raw query string ("?c=7C3AED&t=dark" or without
// the leading "?"), tolerating garbage - the wasm entry's front door.
func ModelFromQuery(search string, embed bool) Model {
	raw := strings.TrimPrefix(search, "?")
	q, err := url.ParseQuery(raw)
	if err != nil {
		return curatedModel(1, "", "", embed)
	}
	return ModelFromValues(q, embed)
}

// FileStem names the downloadable artifacts after the palette.
func FileStem(m Model) string {
	lower := strings.ToLower(m.Pal.Name)
	dashed := strings.ReplaceAll(lower, " ", "-")
	noHash := strings.ReplaceAll(dashed, "#", "")
	noOpen := strings.ReplaceAll(noHash, "(", "")
	return "palette-" + strings.ReplaceAll(noOpen, ")", "")
}
