// Code generated by goplus from view.goml. DO NOT EDIT.
//goplus:v v0.28.0

package web

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"goforge.dev/palettegen/palette"
	"strings"
)

func inkFor(sh palette.Shade) string {
	if palette.LumaOf(sh) > 150.0 {
		return "#102A43"
	}
	return "#FFFFFF"
}

func hslLabel(sh palette.Shade) string {
	return fmt.Sprintf("hsl(%d, %d%%, %d%%)", int(sh.H), int(sh.S), int(sh.L))
}

func escapeHTML(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(s, "&", "&amp;"), "<", "&lt;"), ">", "&gt;")
}

func swatchCell(sh palette.Shade) string {
	return "<div class=\"sw\" style=\"background:" + sh.Hex + ";color:" + inkFor(sh) + "\">" + "<span class=\"sw-hex\">" + sh.Hex + "</span>" + "<span class=\"sw-hsl\">" + hslLabel(sh) + "</span>" + "</div>"
}

func scaleBlock(sc palette.Scale) string {
	cells := ""
	for _, sh := range sc.Shades {
		cells = cells + swatchCell(sh)
	}
	return "<div class=\"scale\">" + "<div class=\"scale-head\"><h4>" + sc.Name + "</h4>" + "<span class=\"scale-range\">900 &#8594; 50 &#183; darkest to lightest</span></div>" + "<div class=\"scale-grid\">" + cells + "</div>" + "</div>"
}

func categorySection(title string, caption string, scales []palette.Scale) string {
	blocks := ""
	for _, sc := range scales {
		blocks = blocks + scaleBlock(sc)
	}
	return "<section class=\"category\"><h3>" + title + "</h3>" + "<p class=\"caption\">" + caption + "</p>" + blocks + "</section>"
}

//goplus:enum MaybeScale
//goplus:derive off
type MaybeScale interface{ isMaybeScale() }

//goplus:variant (MaybeScale) ScaleSome(Sc palette.Scale)
type ScaleSome struct {
	Sc palette.Scale
}

func (ScaleSome) isMaybeScale() {}

//goplus:variant (MaybeScale) ScaleNone
type ScaleNone struct{}

func (ScaleNone) isMaybeScale() {}

func isDangerHue(h float64) bool {
	return h < 35.0 || h >= 330.0
}

func isWarningHue(h float64) bool {
	return h >= 35.0 && h < 80.0
}

func isSuccessHue(h float64) bool {
	return h >= 80.0 && h < 170.0
}

// Supporting scales first, then primaries: when a semantic scale was
// skipped because the primary already owns that hue, the primary serves.
func contextScales(p palette.Palette) []palette.Scale {
	out := make([]palette.Scale, 0)
	for _, sc := range p.Supporting {
		out = append(out, sc)
	}
	for _, sc := range p.Primary {
		out = append(out, sc)
	}
	return out
}

func findScale(scales []palette.Scale, pred func(float64) bool) MaybeScale {
	for _, sc := range scales {
		if len(sc.Shades) == 10 && pred(sc.Shades[4].H) {
			return ScaleSome{Sc: sc}
		}
	}
	return ScaleNone{}
}

func alertHTML(sc palette.Scale, leadIn string, rest string) string {
	sh := sc.Shades
	return "<div class=\"alert\" style=\"background:" + sh[9].Hex + ";border-left:4px solid " + sh[4].Hex + ";color:" + sh[1].Hex + "\"><strong>" + leadIn + "</strong> " + rest + "</div>"
}

func alertRow(ms MaybeScale, leadIn string, rest string) string {
	switch __gp_m0 := any(ms).(type) {
	case ScaleSome:
		sc := __gp_m0.Sc

		return alertHTML(sc, leadIn, rest)
	case ScaleNone:

		return ""
	default:
		panic("goplus: impossible enum value in match")
	}
}

func tile(label string, body string) string {
	return "<div class=\"tile\"><span class=\"tile-label\">" + label + "</span>" + body + "</div>"
}

func chipFor(p palette.Palette) string {
	if len(p.Supporting) == 0 {
		return ""
	}
	su := p.Supporting[len(p.Supporting)-1].Shades
	return "<span class=\"chip\" style=\"background:" + su[8].Hex + ";color:" + su[1].Hex + "\">On track</span>"
}

// The same card twice: once on a light ground, once on a dark one. The
// point is the near miss - a palette that only works on white is not done.
func demoCard(p palette.Palette, dark bool) string {
	pr := p.Primary[0].Shades
	nu := p.Neutrals[0].Shades
	var __gp_v0 string
	if dark {
		__gp_v0 = nu[0].Hex
	} else {
		__gp_v0 = nu[8].Hex
	}
	ground := __gp_v0
	var __gp_v1 string
	if dark {
		__gp_v1 = nu[1].Hex
	} else {
		__gp_v1 = "#FFFFFF"
	}
	card := __gp_v1
	var __gp_v2 string
	if dark {
		__gp_v2 = nu[9].Hex
	} else {
		__gp_v2 = nu[0].Hex
	}
	head := __gp_v2
	var __gp_v3 string
	if dark {
		__gp_v3 = nu[7].Hex
	} else {
		__gp_v3 = nu[3].Hex
	}
	body := __gp_v3
	var __gp_v4 string
	if dark {
		__gp_v4 = pr[7].Hex
	} else {
		__gp_v4 = pr[2].Hex
	}
	ghostInk := __gp_v4
	return "<div class=\"tile-body ground\" style=\"background:" + ground + "\">" + "<div class=\"demo-card\" style=\"background:" + card + "\">" + "<h3 style=\"color:" + head + ";margin:0\">Quarterly report</h3>" + "<p style=\"color:" + body + "\">Revenue is up 12% since the redesign shipped. The board wants details Thursday.</p>" + chipFor(p) + "<div class=\"demo-actions\">" + "<button type=\"button\" class=\"demo-btn\" style=\"background:" + pr[4].Hex + ";color:" + inkFor(pr[4]) + "\">Share report</button>" + "<button type=\"button\" class=\"demo-btn\" style=\"background:transparent;color:" + ghostInk + ";box-shadow: inset 0 0 0 1.5px " + pr[4].Hex + "\">Export</button>" + "</div></div></div>"
}

func alertsTile(p palette.Palette) string {
	pool := contextScales(p)
	nu := p.Neutrals[0].Shades
	rows := alertRow(findScale(pool, isSuccessHue), "Saved.", "Your palette is safely in the export.") + alertRow(findScale(pool, isWarningHue), "Heads up.", "Very light text needs the darker shades to stay readable.") + alertRow(findScale(pool, isDangerHue), "Export failed.", "The disk is full; nothing was written.")
	var __gp_v5 string
	if rows == "" {
		__gp_v5 = "<p class=\"caption\">This palette carries no semantic hues.</p>"
	} else {
		__gp_v5 = rows
	}
	content := __gp_v5
	return "<div class=\"tile-body ground\" style=\"background:" + nu[9].Hex + "\">" + content + "</div>"
}

func navTile(p palette.Palette) string {
	pr := p.Primary[0].Shades
	return "<div class=\"tile-body\"><div class=\"nav-demo\" style=\"background:" + pr[0].Hex + "\">" + "<strong style=\"color:" + pr[9].Hex + "\">Forge</strong>" + "<a style=\"color:" + pr[7].Hex + "\">Overview</a>" + "<a style=\"background:" + pr[4].Hex + ";color:" + inkFor(pr[4]) + "\">Reports</a>" + "<a style=\"color:" + pr[7].Hex + "\">Settings</a>" + "</div></div>"
}

func typeTile(p palette.Palette) string {
	nu := p.Neutrals[0].Shades
	return "<div class=\"tile-body ground type-demo\" style=\"background:" + nu[9].Hex + "\">" + "<p style=\"color:" + nu[0].Hex + ";font-size:20px;font-weight:700\">Dashboard</p>" + "<p style=\"color:" + nu[3].Hex + "\">Hierarchy comes from the greys: darkest for headings, mid for body text.</p>" + "<p style=\"color:" + nu[5].Hex + ";font-size:13px\">Caption and metadata &#183; updated 12 minutes ago</p>" + "</div>"
}

func formTile(p palette.Palette) string {
	pr := p.Primary[0].Shades
	nu := p.Neutrals[0].Shades
	return "<div class=\"tile-body ground\" style=\"background:" + nu[9].Hex + "\">" + "<label style=\"color:" + nu[2].Hex + "\">Work email</label>" + "<input type=\"text\" class=\"mock-input\" placeholder=\"you@example.com\" aria-label=\"Work email (demo)\" style=\"background:#FFFFFF;border:1px solid " + nu[6].Hex + ";color:" + nu[1].Hex + "\">" + "<label style=\"color:" + nu[2].Hex + "\">Team name (focused)</label>" + "<input type=\"text\" class=\"mock-input\" value=\"Design systems\" aria-label=\"Team name (demo)\" style=\"background:#FFFFFF;border:1px solid " + pr[4].Hex + ";box-shadow:0 0 0 3px " + pr[8].Hex + ";color:" + nu[1].Hex + "\">" + "<button type=\"button\" class=\"demo-btn\" style=\"background:" + pr[4].Hex + ";color:" + inkFor(pr[4]) + "\">Create team</button>" + "</div>"
}

func contextSection(p palette.Palette) string {
	if len(p.Primary) == 0 || len(p.Neutrals) == 0 {
		return ""
	}
	if len(p.Primary[0].Shades) != 10 || len(p.Neutrals[0].Shades) != 10 {
		return ""
	}
	return "<section class=\"category\"><h3>In context</h3>" + "<p class=\"caption\">A palette only proves itself in use. The same colors doing their actual jobs - and doing them on light and dark grounds alike.</p>" + "<div class=\"context-grid\">" + tile("On a light ground", demoCard(p, false)) + tile("On a dark ground", demoCard(p, true)) + tile("Semantic alerts", alertsTile(p)) + tile("Text hierarchy", typeTile(p)) + tile("Navigation", navTile(p)) + tile("Forms &amp; focus", formTile(p)) + "</div></section>"
}

func themeLink(m Model, value string, label string) string {
	var __gp_v6 string
	if value == "" {
		__gp_v6 = "?" + m.QS
	} else {
		__gp_v6 = "?" + m.QS + "&amp;t=" + value
	}
	href := __gp_v6
	var __gp_v7 string
	if m.Theme == value {
		__gp_v7 = " class=\"on\""
	} else {
		__gp_v7 = ""
	}
	cls := __gp_v7
	return "<a" + cls + " href=\"" + href + "\">" + label + "</a>"
}

func themeToggle(m Model) string {
	return "<nav class=\"theme-toggle\" aria-label=\"Color scheme\">" + themeLink(m, "", "Auto") + themeLink(m, "light", "Light") + themeLink(m, "dark", "Dark") + "</nav>"
}

func themeField(m Model) string {
	if m.Theme == "" {
		return ""
	}
	return "<input type=\"hidden\" name=\"t\" value=\"" + m.Theme + "\">"
}

func curatedOptions(selectedID int) string {
	out := ""
	for _, b := range palette.Curated() {
		var __gp_v8 string
		if b.ID == selectedID {
			__gp_v8 = " selected"
		} else {
			__gp_v8 = ""
		}
		mark := __gp_v8
		names := ""
		for _, sc := range b.Primary {
			var __gp_v9 string
			if names == "" {
				__gp_v9 = sc.Name
			} else {
				__gp_v9 = names + " + " + sc.Name
			}
			names = __gp_v9
		}
		out = out + fmt.Sprintf("<option value=\"%d\"%s>Palette %d &#183; %s</option>", b.ID, mark, b.ID, names)
	}
	return out
}

func controls(m Model) string {
	return "<div class=\"controls\">" + "<form class=\"gen\" method=\"get\">" + themeField(m) + "<label class=\"field\"><span>Starting color</span>" + "<input type=\"color\" name=\"c\" value=\"" + pickerHex(m) + "\"></label>" + "<label class=\"field\"><span>Exact hex (optional, wins if filled)</span>" + "<input type=\"text\" name=\"hx\" placeholder=\"" + pickerHex(m) + "\" " + "pattern=\"#?[0-9a-fA-F]{3}([0-9a-fA-F]{3})?\"></label>" + "<button class=\"primary\" type=\"submit\">Generate palette</button>" + "</form>" + "<form class=\"curated\" method=\"get\">" + themeField(m) + "<label class=\"field\"><span>Or start from the book</span>" + "<select name=\"p\">" + curatedOptions(m.CuratedID) + "</select></label>" + "<button class=\"ghost\" type=\"submit\">Open book palette</button>" + "</form>" + "</div>"
}

func jsonSection(m Model) string {
	return "<section class=\"category\"><h3>Take it with you</h3>" + "<p class=\"caption\">The buttons above download files; this block is for pasting straight into a tailwind config, a theme file, or a teammate's chat.</p>" + "<details class=\"json-view\"><summary>Show the JSON</summary>" + "<pre><code>" + escapeHTML(string(palette.ToJSON(m.Pal))) + "</code></pre>" + "</details></section>"
}

func b64OfBytes(bs []byte) string {
	enc := base64.StdEncoding
	return enc.EncodeToString(bs)
}

func noBuf() []byte {
	return make([]byte, 0)
}

func pdfDataURL(p palette.Palette) string {
	buf := bytes.NewBuffer(noBuf())
	err := palette.WritePDF(buf, p)
	if err != nil {
		return ""
	}
	return "data:application/pdf;base64," + b64OfBytes(buf.Bytes())
}

func jsonDataURL(p palette.Palette) string {
	return "data:application/json;base64," + b64OfBytes(palette.ToJSON(p))
}

// Server pages link the endpoints; the wasm build hands out the files
// directly as data: URLs, since there is no server behind it.
func downloadLinks(m Model) string {
	if m.Embed {
		return "<a class=\"dl pdf\" download=\"" + FileStem(m) + ".pdf\" href=\"" + pdfDataURL(m.Pal) + "\">Download PDF</a>" + "<a class=\"dl json\" download=\"" + FileStem(m) + ".json\" href=\"" + jsonDataURL(m.Pal) + "\">Download JSON</a>"
	}
	return "<a class=\"dl pdf\" href=\"palette.pdf?" + m.QS + "\">Download PDF</a>" + "<a class=\"dl json\" href=\"palette.json?" + m.QS + "\">Download JSON</a>"
}

func resultSection(m Model) string {
	return "<div class=\"result-head\"><h2>" + m.Pal.Name + "</h2>" + "<div class=\"downloads\">" + downloadLinks(m) + "</div></div>" + "<p class=\"basis\">" + m.Pal.Basis + "</p>" + categorySection("Primary", "Your product's voice. Use these for primary actions, links, navigation, icons - the splashes of color that determine the overall look.", m.Pal.Primary) + categorySection("Neutrals", "The workhorse. Most of your UI is this: text, backgrounds, panels, borders, secondary buttons.", m.Pal.Neutrals) + categorySection("Supporting", "The seasoning, used sparingly: success, warning and danger states, plus accents that keep the primary color special.", m.Pal.Supporting) + contextSection(m.Pal) + jsonSection(m)
}

// The goforge.dev project metadata, worn the way the other tool pages
// wear it: a version pill, the install command, and the standard links.
func projectMeta() string {
	return "<div class=\"meta\">" + "<span class=\"pill\"><span class=\"dot\"></span>" + Version + "</span>" + "<code class=\"install\"><span class=\"prompt\">$</span> go install goforge.dev/palettegen@latest</code>" + "<nav class=\"meta-links\" aria-label=\"Project links\">" + "<a href=\"https://github.com/brain-fuel/palettegen\">Source repository</a>" + "<a href=\"https://pkg.go.dev/goforge.dev/palettegen\">pkg.go.dev</a>" + "<a href=\"https://goforge.dev/\">goforge.dev</a>" + "</nav></div>"
}

func noteBanner(m Model) string {
	if m.Note == "" {
		return ""
	}
	return "<p class=\"note\">" + m.Note + "</p>"
}

func htmlAttrs(m Model) string {
	if m.Theme == "" {
		return ""
	}
	return " data-theme=\"" + m.Theme + "\""
}

func headAssets(m Model) string {
	if m.Embed {
		return "<style>\n" + EmbeddedCSS(m.Pal) + "\n</style>\n"
	}
	return "<link rel=\"stylesheet\" href=\"style.css\">\n" + "<style>\n" + ThemeCSS(m.Pal) + "\n</style>\n"
}

func RenderPage(m Model) string {
	return "<!doctype html>\n<html lang=\"en\"" + htmlAttrs(m) + ">\n<head>\n" + "<meta charset=\"utf-8\">\n" + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" + "<title>Palette Forge - complete UI color palettes</title>\n" + headAssets(m) + "</head>\n<body>\n<main>\n" + "<header class=\"hero\">" + "<div class=\"hero-top\"><h1>Palette <span class=\"fleck\">Forge</span></h1>" + themeToggle(m) + "</div>" + "<p class=\"promise\">Pick one color. In seconds you have the full system a real interface needs - ten shades each of a primary, matched neutrals, and supporting colors - not five pretty swatches that fall apart in practice.</p>" + projectMeta() + "</header>\n" + noteBanner(m) + controls(m) + resultSection(m) + "\n<footer>Palettes and method from <em>Refactoring UI: Color Palettes</em> and <em>Refactoring UI</em> (Adam Wathan &amp; Steve Schoger). " + "UX after Joe Natoli; UI after Leonardo da Vinci and Patrick Henry Winston. " + "Written in goml on the <a href=\"https://goforge.dev\">goforge</a> toolchain. " + "<a href=\"https://github.com/brain-fuel/palettegen/blob/main/LICENSE\">MIT licensed</a>.</footer>\n" + "</main>\n</body>\n</html>\n"
}
